---
title: "1_QCFilter"
output: html_document
date: "2025-05-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Load libraries
```{r}
library(dplyr)
library(vcfR)
library(adegenet)
library(data.table)
```


#Step 1: Load VCF and fix sample names 
#Load data
```{r}
vcf <- read.vcfR("ISOPORA_variants.vcf")

# Clean sample names
sample_names <- colnames(vcf@gt)[-1]
shortened_names <- sub("^([^-]+-[^-]+).*", "\\1", sample_names)
colnames(vcf@gt)[-1] <- shortened_names
```


#1. QC Filtering - all samples
##1.1 Convert genotypes to numeric format
```{r}
gt <- extract.gt(vcf, element = "GT", as.numeric = FALSE)
geno_num <- matrix(NA, nrow = nrow(gt), ncol = ncol(gt))

for (i in 1:nrow(gt)) {
  for (j in 1:ncol(gt)) {
    g <- gt[i, j]
    geno_num[i, j] <- ifelse(g %in% c("0/0", "0|0"), 0,
                       ifelse(g %in% c("0/1", "1/0", "0|1", "1|0"), 1,
                       ifelse(g %in% c("1/1", "1|1"), 2, NA)))
  }
}
```


##1.2 Loci filtering
```{r}
# Locus missingness
missing_per_locus <- rowMeans(is.na(geno_num))

# Minor allele count (MAC)
mac <- apply(geno_num, 1, function(x) {
  x <- x[!is.na(x)]
  # count whichever allele is rarer
  min(sum(x), 2*length(x) - sum(x))
})

# Keep loci: missingness ≤ 20%, MAC ≥ 3 (adjust threshold as needed)
keep_loci <- which(missing_per_locus <= 0.2 & mac >= 3)

# Apply locus filter
vcf_filtered <- vcf[keep_loci, ]

# Individual filtering
gt_filtered <- extract.gt(vcf_filtered, element = "GT", as.numeric = FALSE)
missing_per_ind <- colMeans(is.na(gt_filtered))
keep_inds <- names(missing_per_ind[missing_per_ind <= 0.5])
vcf_filtered <- vcf_filtered[, c(TRUE, colnames(gt_filtered) %in% keep_inds)]

# Remove 2020 individuals
keep_inds <- colnames(vcf_filtered)[-1]
vcf_filtered <- vcf_filtered[, c(TRUE, !grepl("-20", keep_inds))]
```


##1.3 Genind conversion / Joining metadata
```{r}
# Convert VCF to genind
iso_gen <- vcfR2genind(vcf_filtered)

# Keep only up to "-24" in individual names
indNames(iso_gen) <- sub("(-24).*", "\\1", indNames(iso_gen))

# Remove individuals with '-20' or '-24b'
inds_filtered <- indNames(iso_gen)[!grepl("-20|-24b", indNames(iso_gen))]
iso_gen <- iso_gen[inds_filtered, ]

# Read metadata
meta <- fread("Iso_Meta2024.csv")

# Clean metadata sample IDs (keep only up to "-24")
meta_clean <- meta %>%
  mutate(SampleID = sub("(-24).*", "\\1", trimws(as.character(VialID))))

# Filter and order metadata to match cleaned genind individuals
meta_ordered <- meta_clean %>%
  filter(SampleID %in% indNames(iso_gen)) %>%
  arrange(match(SampleID, indNames(iso_gen)))
```


```{r}
iso_gen <- vcfR2genind(vcf_filtered)

# Check for match
inds <- indNames(iso_gen)
inds_clean <- trimws(inds)
meta_clean <- meta %>% mutate(SampleID = trimws(as.character(VialID)))

write.csv(x = meta_clean, file ="meta_clean.csv")

# Filter out '-20' samples from inds
inds_filtered <- inds_clean[!grepl("-20|-24b", inds_clean)]

# Filter metadata to match and remove '-20' individuals
meta_ordered_iso <- meta_clean %>%
  filter(SampleID %in% inds_filtered) %>%
  arrange(match(SampleID, inds_filtered))

# Also update genind object to remove those individuals
iso_gen_full <- iso_gen[!grepl("-20|-24b", indNames(iso_gen)), ]

# #meta trimmed
# iso_meta <- read.csv("Acro_Meta2024.csv") %>%
#   rename(SampleID = VialID)
# 
# # Match and merge metadata
# inds <- indNames(acro_gen_full)
# meta_trimmed <- merge(data.table(SampleID = inds), acro_meta, by = "SampleID", all.x = TRUE)
# meta_trimmed <- meta_trimmed[match(inds, meta_trimmed$SampleID), ]

```


##Add population level assignments 
```{r}
# 3. Ensure metadata rows are ordered to match genind individuals
# indNames() gives the individual IDs in the genind
meta <- meta_ordered_iso %>%
  filter(SampleID %in% indNames(iso_gen_full)) %>%   # keep only samples in genind
  arrange(match(SampleID, indNames(iso_gen_full)))   # reorder to match genind

# 4. Assign population/reef to genind
pop_vector <- meta$Reef  
pop(iso_gen_full) <- as.factor(pop_vector)

# 5. Verify
table(pop(iso_gen_full))  # should show number of individuals per reef

meta_trimmed <- meta
save(meta_trimmed, file = "meta_trimmed.RData")
```


```{r}
save(iso_gen_full, file = "iso_gen_full.RData")

load("iso_gen_full.RData")
```

```{r}
coords <- meta[match(indNames(iso_gen_full), meta$SampleID), c("GPS S", "GPS E")]
```

```{r}
write.table(coords,
            file = "coords.txt",
            sep = "\t",
            quote = FALSE,
            row.names = TRUE,
            col.names = FALSE)
```



```{r}
# Read raw lines
lines <- readLines("geno_matrix.txt")
length(lines)      # number of rows

# Check the number of columns per line
col_counts <- sapply(lines, function(x) length(strsplit(x, "\\s+")[[1]]))
table(col_counts)  # see the distribution of column counts
```

```{r}
save(iso_gen, file = "iso_gen.RData")
save(meta_ordered_iso, file = "meta_ordered_iso.RData")
```

